"""rename address

Revision ID: 91019e2f5319
Revises: 9220facbb445
Create Date: 2025-01-22 10:06:55.233118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91019e2f5319'
down_revision = '9220facbb445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
